/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
/**
 *
 * @author Ismail
 */
public class MakeReservation extends javax.swing.JFrame {
    private String roomType;
    private int roomNumber;
    /**
     * Creates new form Payments
     */
    
    public MakeReservation() {
    initComponents();
    hideFields();
}

// Constructor for when room details are available
public MakeReservation(int roomNumber, String roomType) {
    this.roomNumber = roomNumber;
    this.roomType = roomType;
    initComponents();
    setRoomDetails(roomNumber, roomType);
    hideFields();
}

private void hideFields() {
    txtoriginalprice.setVisible(true);
    
}

private void setRoomDetails(int roomNumber, String roomType) {
    txtroomno.setText(String.valueOf(roomNumber)); // Display room number
    txtroomtype.setText(roomType); // Display room type
}

private long getNumberOfNights() {
    LocalDate checkInDate = txtcheckin.getDatoFecha().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    LocalDate checkOutDate = txtcheckout.getDatoFecha().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    return ChronoUnit.DAYS.between(checkInDate, checkOutDate);
}

private double getPricePerNight(String roomType) {
    double pricePerNight = 0.0;
    String query = "SELECT price_per_night FROM rooms WHERE room_type = ? AND availability_status = 'Available' LIMIT 1";

    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "WJ28@krhps");
         PreparedStatement pst = con.prepareStatement(query)) {

        // Set the parameter for the room type
        pst.setString(1, roomType);

        // Execute the query and process the result
        try (ResultSet rs = pst.executeQuery()) {
            if (rs.next()) {
                pricePerNight = rs.getDouble("price_per_night");
            }
        }

    } catch (SQLException e) {
        e.printStackTrace();
    }

    return pricePerNight;
}

private void calculateOriginalPrice() {
    if (!validateReservationFields()) {
        return; // Ensure fields are valid before calculation
    }

    String roomType = txtroomtype.getText().trim();
    long numberOfNights = getNumberOfNights();
    double pricePerNight = getPricePerNight(roomType);
    double originalPrice = pricePerNight * numberOfNights;

    txtoriginalprice.setText(String.format("PKR %.2f", originalPrice));
    
    txtoriginalprice.setVisible(true); 
}

// Validates the reservation fields 
private boolean validateReservationFields() {
    if (txtcname.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter the customer name.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    if (txtcheckin.getDatoFecha() == null) {
        JOptionPane.showMessageDialog(this, "Please select a check-in date.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    if (txtcheckout.getDatoFecha() == null) {
        JOptionPane.showMessageDialog(this, "Please select a check-out date.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    if (txtroomno.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a room number.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    if (txtroomtype.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a room type.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    
    
    return true;
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtroomtype = new app.bolivia.swing.JCTextField();
        txtcname = new app.bolivia.swing.JCTextField();
        txtroomno = new app.bolivia.swing.JCTextField();
        txtoriginalprice = new app.bolivia.swing.JCTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtcheckout = new rojeru_san.componentes.RSDateChooser();
        txtcheckin = new rojeru_san.componentes.RSDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Make Reservations");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("I have reservations about everything I do");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 260, 20));

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel8.setText("Back");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 0, 20, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 120));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtroomtype.setPlaceholder("Enter room type...");
        jPanel1.add(txtroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 400, 40));

        txtcname.setPlaceholder("Enter Customer name...");
        jPanel1.add(txtcname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 400, 40));

        txtroomno.setPlaceholder("Enter room no...");
        jPanel1.add(txtroomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 400, 40));

        txtoriginalprice.setPlaceholder("Enter original price...");
        jPanel1.add(txtoriginalprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 400, 40));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, 100, 40));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Calculate Total");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, 50));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel9.setText("Original Price");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel10.setText("Customer Name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel11.setText("Check-In Date");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel12.setText("Check-Out Date");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel13.setText("Room Number");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel14.setText("Room Type");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        txtcheckout.setColorBackground(new java.awt.Color(0, 153, 153));
        txtcheckout.setColorDiaActual(new java.awt.Color(0, 153, 153));
        txtcheckout.setColorForeground(new java.awt.Color(0, 0, 0));
        txtcheckout.setPlaceholder("Enter due date...");
        jPanel1.add(txtcheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 400, -1));

        txtcheckin.setColorBackground(new java.awt.Color(0, 153, 153));
        txtcheckin.setColorDiaActual(new java.awt.Color(0, 153, 153));
        txtcheckin.setColorForeground(new java.awt.Color(0, 0, 0));
        txtcheckin.setPlaceholder("Enter issue date...");
        jPanel1.add(txtcheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 400, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 880, 540));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Second.jpeg"))); // NOI18N
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 340, 220));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Want to refresh price? Click here.");
        jPanel2.add(jLabel4);

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 240, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 490, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        HomePage home=new HomePage();
       home.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if (validateReservationFields()) {
    // Collect data from the reservation form
    String customerName = txtcname.getText();

    // Get the date values from JDateChooser
    java.util.Date checkInDateUtil = txtcheckin.getDatoFecha(); // Assuming txtCheckInDate is a JDateChooser
    java.util.Date checkOutDateUtil = txtcheckout.getDatoFecha(); // Assuming txtCheckOutDate is a JDateChooser

    // Convert java.util.Date to java.sql.Date
    java.sql.Date checkInDate = new java.sql.Date(checkInDateUtil.getTime());
    java.sql.Date checkOutDate = new java.sql.Date(checkOutDateUtil.getTime());

    // Get the room type from text field
    String roomType = txtroomtype.getText().trim(); // Assuming txtRoomType is a JTextField

    // Get the room number from text field and convert it to String
    String roomNumberText = txtroomno.getText().trim(); // Assuming txtRoomNumber is a JTextField

    // Ensure the original price field is not empty
    String originalPriceText = txtoriginalprice.getText().replace("PKR ", "").trim();

    double originalPrice = originalPriceText.isEmpty() ? 0.0 : Double.parseDouble(originalPriceText);

    // Create a new Payment instance and pass the collected data
    Payements paymentPage = new Payements(customerName, checkInDate, checkOutDate, roomNumberText, roomType, originalPrice, 0.0);
    paymentPage.setVisible(true);

    // Optionally, close the Reservation page
    this.dispose();
} else {
    // If validation fails, show an error message or handle it accordingly
    JOptionPane.showMessageDialog(this, "Please fill in all required fields correctly.", "Validation Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private rojeru_san.componentes.RSDateChooser txtcheckin;
    private rojeru_san.componentes.RSDateChooser txtcheckout;
    private app.bolivia.swing.JCTextField txtcname;
    private app.bolivia.swing.JCTextField txtoriginalprice;
    private app.bolivia.swing.JCTextField txtroomno;
    private app.bolivia.swing.JCTextField txtroomtype;
    // End of variables declaration//GEN-END:variables
}
