/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
/**
 *
 * @author Ismail
 */
public class SearchRooms extends javax.swing.JFrame {

    /**
     * Creates new form SearchRooms
     */
    public SearchRooms() {
        initComponents();
        setSearchRoomsDataToTable();
    }
    DefaultTableModel model;
    public void setSearchRoomsDataToTable() {
        try {
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "WJ28@krhps");
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery("select * from rooms");
             
             while(rs.next()) {
                String roomId = rs.getString("room_id");
                String roomNumber = rs.getString("room_number");
                String roomType = rs.getString("room_type");
                String price = rs.getString("price_per_night");
                String status = rs.getString("availability_status");
                
                Object obj[] = {roomId, roomNumber, roomType, price, status};
                model = (DefaultTableModel) tblroom.getModel();
                model.addRow(obj);
                
             }
        }catch (Exception e) {
               e.printStackTrace();
            }
    }
    
    
    private boolean validateRoomType() {
    String selectedRoomType = (String) cbroomtype.getSelectedItem();
    
    if (selectedRoomType == null || selectedRoomType.trim().isEmpty() || selectedRoomType.equals("Select Room type...")) {
        JOptionPane.showMessageDialog(null, "Please select a room type.");
        return false;
    }
    return true;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbroomtype = new javax.swing.JComboBox<>();
        txtroomno = new app.bolivia.swing.JCTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblroom = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtroomtype = new app.bolivia.swing.JCTextField();

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel3.setText("Room Number :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 100, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, 100, 40));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel4.setText("Room Type :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 80, -1));

        cbroomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single room", "Double room", "Triple room", "Quad room", "Suite room", "Bed room", "Studio room" }));
        jPanel2.add(cbroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 220, 40));
        jPanel2.add(txtroomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 230, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1370, 100));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Find Your Perfect Room");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("My Heart Belongs To Room Service");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 220, 20));

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel8.setText("Back");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 120));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblroom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblroom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room ID", "Room Number", "Room Type", "Price Per Night", "Status"
            }
        ));
        tblroom.setRowHeight(30);
        tblroom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblroomMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblroom);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 990, 290));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Show All Avalaible Rooms");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 310, 40));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Book Now");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 360, 160, 40));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel6.setText("Room Type");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 100, -1));

        txtroomtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtroomtypeActionPerformed(evt);
            }
        });
        jPanel4.add(txtroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 230, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 1370, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        HomePage home=new HomePage();
       home.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (validateRoomType()) {
        String selectedRoomType = (String) cbroomtype.getSelectedItem();
        
        // Clear the table
        DefaultTableModel model = (DefaultTableModel) tblroom.getModel();
        model.setRowCount(0);
        
        // Query database and populate table
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "WJ28@krhps");
             PreparedStatement stmt = con.prepareStatement("SELECT * FROM rooms WHERE room_type = ? AND availability_status = 'Available'")) {
            stmt.setString(1, selectedRoomType);
            ResultSet rs = stmt.executeQuery();
            
            boolean roomsFound = false; // Flag to check if any rooms are found
            
            while (rs.next()) {
                // Fetch room details from result set
                String roomId = rs.getString("room_id");
                String roomNumber = rs.getString("room_number");
                String roomType = rs.getString("room_type");
                String price = rs.getString("price_per_night");
                String status = rs.getString("availability_status");
                
                Object[] row = { roomId, roomNumber, roomType, price, status };
                model.addRow(row);
                
                               
                roomsFound = true; // Set flag to true if at least one room is found
            }
            
            if (!roomsFound) {
                JOptionPane.showMessageDialog(this, "No rooms available for the selected type.", "No Results", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "An error occurred while retrieving data.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblroom.getModel();
    model.setRowCount(0);
    
    // Query database and populate table
    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "WJ28@krhps");
         PreparedStatement stmt = con.prepareStatement("SELECT * FROM rooms WHERE availability_status = 'Available'")) {
        ResultSet rs = stmt.executeQuery();
        
        while(rs.next()) {
                String roomId = rs.getString("room_id");
                String roomNumber = rs.getString("room_number");
                String roomType = rs.getString("room_type");
                String price = rs.getString("price_per_night");
                String status = rs.getString("availability_status");
                
                
                Object obj[] = {roomId, roomNumber, roomType, price, status};
                model = (DefaultTableModel) tblroom.getModel();
                model.addRow(obj);
                
             }
        } catch (SQLException e) {
            e.printStackTrace();
    }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblroomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblroomMouseClicked
        int selectedRow = tblroom.getSelectedRow();
    if (selectedRow >= 0) {
        String roomNumber = (String) tblroom.getValueAt(selectedRow, 1);
        String roomType = (String) tblroom.getValueAt(selectedRow, 2);
        
        // Populate text fields with selected room details
        txtroomno.setText(roomNumber);
        txtroomtype.setText(roomType);
    }
    }//GEN-LAST:event_tblroomMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String roomNumberStr = txtroomno.getText().trim();
    String roomType = txtroomtype.getText().trim();
    
    if (!roomNumberStr.isEmpty() && !roomType.isEmpty()) {
        try {
            // Convert room number from String to int
            int roomNumber = Integer.parseInt(roomNumberStr);
            
            // Open the reservation page and pass room details
            MakeReservation reserv = new MakeReservation(roomNumber, roomType);
            reserv.setVisible(true);
            this.dispose(); // Close the search room page if needed
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid room number format.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a room first.", "Selection Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtroomtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtroomtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtroomtypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchRooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbroomtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblroom;
    private app.bolivia.swing.JCTextField txtroomno;
    private app.bolivia.swing.JCTextField txtroomtype;
    // End of variables declaration//GEN-END:variables
}
