/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ismail
 */
public class ViewBooking extends javax.swing.JFrame {

    /**
     * Creates new form SearchRooms
     */
    public ViewBooking() {
        initComponents();
        setReservationDataToTable();
    }
    DefaultTableModel model;
    public void setReservationDataToTable() {
        try {
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "WJ28@krhps");
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery("select * from reservations");
             
             while(rs.next()) {
                String Id = rs.getString("reservation_id");
                String name = rs.getString("customer_name");
                String checkIn = rs.getString("check_in_date");
                String checkOut = rs.getString("check_out_date");
                String roomNo = rs.getString("room_number");
                String roomType = rs.getString("room_type");
                String price = rs.getString("original_price");
                String discountApplied = rs.getString("discount_applied");
                String discountPrice = rs.getString("discounted_price");
                String paymentMethod = rs.getString("payment_method");
                String status = rs.getString("payment_status");
                               
                Object obj[] = {Id, name, checkIn, checkOut, roomNo, roomType, price, discountApplied, 
                               discountPrice, paymentMethod, status};
                model = (DefaultTableModel) tblbooking.getModel();
                 model.addRow(obj);
                
             }
        }catch (Exception e) {
               e.printStackTrace();
            }
    }
    
     private void refreshData() {
    // Clear existing data in the table
    DefaultTableModel model = (DefaultTableModel) tblbooking.getModel();
    model.setRowCount(0);
    
    JOptionPane.showMessageDialog(this, "Refreshed Booking Details!");
    // Re-fetch and display updated data
    setReservationDataToTable();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtcname = new app.bolivia.swing.JCTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbooking = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, 100, 40));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel4.setText("Customer Name :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 120, -1));
        jPanel2.add(txtcname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 320, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1370, 100));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Your Booking Details");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("A hotel room all to myself is my idea of a good time .");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 340, 20));

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel8.setText("Back");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 120));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblbooking.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblbooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rservation", "Customer Name", "Check-In", "Check-Out", "Room No", "Roome Type", "Price", "Discount Applied", "Discount Price", "Payment Method", "Payment Status"
            }
        ));
        tblbooking.setRowHeight(30);
        jScrollPane1.setViewportView(tblbooking);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 1320, 300));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 170, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 1370, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    String customerName = ""; // Initialize customerName to an empty string
    model = (DefaultTableModel) tblbooking.getModel();
    model.setRowCount(0); // Clear existing rows

    String query = "SELECT * FROM reservations";
    
    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "WJ28@krhps");
         PreparedStatement pst = con.prepareStatement(query)) {
        
        ResultSet rs = pst.executeQuery();
        while (rs.next()) {
            String Id = rs.getString("reservation_id");
            String name = rs.getString("customer_name");
            String checkIn = rs.getString("check_in_date");
            String checkOut = rs.getString("check_out_date");
            String roomNo = rs.getString("room_number");
            String roomType = rs.getString("room_type");
            String price = rs.getString("original_price");
            String discountApplied = rs.getString("discount_applied");
            String discountPrice = rs.getString("discounted_price");
            String paymentMethod = rs.getString("payment_method");
            String status = rs.getString("payment_status");

            Object obj[] = {Id, name, checkIn, checkOut, roomNo, roomType, price, discountApplied, discountPrice, paymentMethod, status};
            model.addRow(obj);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        HomePage home=new HomePage();
       home.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String customerName = txtcname.getText().trim(); // Get the text entered by the user
    model = (DefaultTableModel) tblbooking.getModel();
    model.setRowCount(0); // Clear existing rows

    String query = "SELECT * FROM reservations";
    
    // Add a WHERE clause if a name is entered
    if (!customerName.isEmpty()) {
        query += " WHERE customer_name LIKE ?";
    }

    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "WJ28@krhps");
         PreparedStatement pst = con.prepareStatement(query)) {
        
        // Set the parameter if a name is entered
        if (!customerName.isEmpty()) {
            pst.setString(1, "%" + customerName + "%"); // Use wildcard for partial matches
        }
        
        ResultSet rs = pst.executeQuery();
        while (rs.next()) {
            String Id = rs.getString("reservation_id");
            String name = rs.getString("customer_name");
            String checkIn = rs.getString("check_in_date");
            String checkOut = rs.getString("check_out_date");
            String roomNo = rs.getString("room_number");
            String roomType = rs.getString("room_type");
            String price = rs.getString("original_price");
            String discountApplied = rs.getString("discount_applied");
            String discountPrice = rs.getString("discounted_price");
            String paymentMethod = rs.getString("payment_method");
            String status = rs.getString("payment_status");

            Object obj[] = {Id, name, checkIn, checkOut, roomNo, roomType, price, discountApplied, discountPrice, paymentMethod, status};
            model.addRow(obj);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbooking;
    private app.bolivia.swing.JCTextField txtcname;
    // End of variables declaration//GEN-END:variables
}
